branch-defaults:
  main:
    environment: cocus-challenge-prod
  develop:
    environment: cocus-challenge-dev
  feature/implement-fizzbuzz-logic:
    environment: cocus-challenge-dev
    group_suffix: null
deploy:
  artifact: target/FizzBuzz-0.0.1-SNAPSHOT.jar
global:
  application_name: cocus-challenge
  branch: null
  default_ec2_keyname: cocus-challenge
  default_platform: Corretto 8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
