AWSTemplateFormatVersion: 2010-09-09
Description: >
  AWS CloudFormation Template for provisioning AWS infrastructure for fizzbuzz project

Parameters:
  EnvType:
    Type: String
    Description: Environment type (dev, qa, stg or prod).
    AllowedValues:
      - prod
      - qa
      - stg
      - dev

Resources:

  # *******************************
  # Api Gateway
  # *******************************
  ApiGatewayRest:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: FizzBuzzApi
      Name: fizzbuzz-api-with-auth
      ProtocolType: HTTP
      Target: https://awseb-AWSEB-IQ0RJNWQMLU-1537742411.us-east-1.elb.amazonaws.com/

  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatewayRest
      IntegrationMethod: POST
      IntegrationType: HTTP_PROXY
      IntegrationUri: https://awseb-AWSEB-IQ0RJNWQMLU-1537742411.us-east-1.elb.amazonaws.com/fizzbuzz
      PayloadFormatVersion: 1.0

  RouteFizzBuzz:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayRest
      RouteKey: POST /fizzbuzz